name: build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: ncurses on linux
      if: startsWith(matrix.config.os, 'ubuntu')
      run: sudo apt-get install libncurses5-dev libncursesw5-dev -y

    # - name: ncurses on macos 
    #   if: startsWith(matrix.config.os, 'macos')
    #   run: brew install ...

    - name: make-clean-all
      run: make clean all

    - name: make-clean-test
      run: make clean test
