name: build and test

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      matrix:
        # platform: [ubuntu-latest, macos-latest]
        platform: ubuntu-latest
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: ncurses on linux
      if: startsWith(matrix.platform, 'ubuntu-latest')
      run: sudo apt-get install libncurses5-dev libncursesw5-dev -y

    - name: 'make clean all'
      run: make clean all

    - name: 'make clean test'
      run: make clean test
