name: release binaries and upload artifacts
on:
  push:
    branches: [ develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ develop ]

jobs:
  release:
    name: compile release assets
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: install ncurses on linux
        if: startsWith(matrix.platform, 'ubuntu-latest')
        run: sudo apt-get install libncurses5-dev libncursesw5-dev -y

      - name: install ncurses on macos
        if: startsWith(matrix.platform, 'macos-latest')
        run: |
          brew install ncurses@HEAD
          export PATH="/usr/local/opt/ncurses/bin:$PATH"

      - name: 'make clean test'
        run: make clean test

      - name: 'make clean static-linux'
        if: startsWith(matrix.platform, 'ubuntu-latest')
        run: make clean static-linux

      - name: 'make clean static-darwin'
        if: startsWith(matrix.platform, 'macos-latest')
        run: make clean static-darwin

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: overengineered-${{ matrix.platform }}-static
          path: |
            overengineered
            assets/csv/*
            assets/img/*
            assets/sounds/*.wav
            overengineered.conf.csv
            scoreboard.csv
