name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ncurses
      run: sudo apt-get install libncurses5-dev libncursesw5-dev -y
    - name: make-clean-all
      run: make clean all
    - name: make-clean-test
      run: make clean test
