name: release binaries and upload artifacts

on:
  push:
    branches: [ develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ develop ]

jobs:
  release:
    name: compile release assets
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: install ncurses on linux
        if: startsWith(matrix.platform, 'ubuntu-latest')
        run: sudo apt-get install libncurses5-dev libncursesw5-dev -y

      - name: 'make clean test'
        run: make clean test

      - name: 'make clean all'
        run: make clean all

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ replace(github.ref, 'refs/tags/' }}-${{matrix.platform}}
          body: ${{ github.sha }}
          files: alma 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload artifact
        with:
          name: alma
          path: alma
